export default [
    {id:1,rubro:1,name:"Celulares"},
    {id:2,rubro:1,name:"Tablet"},
    {id:3,rubro:1,name:"Televisores"},
	{id:4,rubro:1,name:"Equipos de Sonido"},
	{id:5,rubro:1,name:"Computadoras"},
	{id:6,rubro:2,name:"Dama"},
	{id:7,rubro:2,name:"Caballero"},
	{id:8,rubro:3,name:"Refrigerador"},
	{id:9,rubro:3,name:"Licuadoras"},
    {id:10,rubro:3,name:"Lavadoras"},
    {id:11,rubro:3,name:"Cocinas"},
	{id:12,rubro:3,name:"Hornos Microondas"},
    {id:13,rubro:3,name:"Ventiladores"},
    {id:14,rubro:4,name:"Reloj"},
	{id:15,rubro:6,name:"Armarios"},
    {id:16,rubro:6,name:"Cajones"},
    {id:17,rubro:6,name:"Sofás y sillones"},
	{id:18,rubro:6,name:"Mesas y sillas"},
    {id:19,rubro:6,name:"Mesitas de noche"},
    {id:20,rubro:6,name:"Colchones"},
	{id:21,rubro:6,name:"Camas"},
    {id:22,rubro:6,name:"Aparatos Electrónicos"},
    {id:23,rubro:6,name:"Tarimas y cabeceras"},
    {id:24,rubro:7,name:"Dama"},
    {id:25,rubro:7,name:"Caballero"},
    {id:26,rubro:8,name:"Zapatillas"}
]